name: so_pysm_models

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - healpy
    - pip:
        - https://github.com/zonca/PySM_public/archive/pysm_light.zip
